# API Credentials of your telegram application created at https://my.telegram.org/apps
api_id: "ID_HERE"
api_hash: "HASH_HERE"

# bot token
bot_token: "TOKEN_HERE"

# Either debug logging is enabled or not
debug: "False"
log_channel: "0"

# socks5
proxy_addr: ""
proxy_port: ""

# ipv6
ipv6: "False"
